### ISSUE TITLE
double quotes support

### ISSUE THREAD

**Issue by oriSomething** [oriSomething/lodash-modules-sublime#4]
today we support only single quotes for import (`import map from 'lodash/map'`), but since in many projects i need to use double quotes instead.

i think of adding a option in the `shift+cmd+p` menu for toggle between the options.

@hawkrives what do you think? do you think there is a better way?

**Comment by hawkrives** [comment]
That sounds fine to me. I prefer single quotes but I'm perfectly fine with an option to switch.

Do you have any idea how to go about doing the menu option? I don't, but I can look into it if you'd prefer.

**Comment by oriSomething** [comment]
i guess something like toggling linter in SublimeLinter.
`lodash imports: to single qoutes` <-> `lodash imports: to double qoutes`
the only thing that bothers me is that the most practical way of doing this, is by using some hack of batch file renaming from `*.sublime-snippet` to something else which sublime doesn't recognize and backword

**Comment by hawkrives** [comment]
I figured we'd provide another set of snippets and just switch between the folders of snippets based on the setting or something.

**Comment by oriSomething** [comment]
i'm actually thinking when there is [this webpack plugin](https://www.npmjs.com/package/lodash-webpack-plugin). i'm not sure if this sublime plugin is needed at all

**Comment by hawkrives** [comment]
My use case is that I like to explicitly list the dependencies for each file.

**Comment by oriSomething** [comment]
Not, needed anymore because of [prettier](/prettier/prettier)

**Comment by hawkrives** [comment]
Sounds good to me!
